import React, { useEffect } from 'react';
import { View, Text, StyleSheet, Image, Platform } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withRepeat,
  withTiming,
  withSequence,
  Easing,
  ZoomIn,
} from 'react-native-reanimated';
import { useAppStore } from '@/lib/store';
import { getItemById } from '@/lib/items';
import type { FairyEmotion } from '@/types';

interface FairyCharacterProps {
  emotion?: FairyEmotion;
  message?: string;
  size?: 'sm' | 'md' | 'lg';
  showMessage?: boolean;
}

const SIZE_CONFIG = {
  sm: { size: 90, container: 100 },
  md: { size: 160, container: 180 },
  lg: { size: 240, container: 260 },
};

export default function FairyCharacter({
  emotion = 'happy',
  message,
  size = 'md',
  showMessage = true,
}: FairyCharacterProps) {
  const cfg = SIZE_CONFIG[size];
  const equippedItems = useAppStore((s) => s.equippedItems || {});

  // Animations
  const floatY = useSharedValue(0);

  useEffect(() => {
    // Floating Animation
    floatY.value = withRepeat(
      withSequence(
        withTiming(-12, { duration: 2500, easing: Easing.inOut(Easing.quad) }),
        withTiming(0, { duration: 2500, easing: Easing.inOut(Easing.quad) }),
      ),
      -1,
      true
    );
  }, []);

  const containerStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: floatY.value }],
  }));

  // Resolve equipped emojis
  const hatItem = equippedItems['모자'] ? getItemById(equippedItems['모자']!) : null;
  const wingItem = equippedItems['날개'] ? getItemById(equippedItems['날개']!) : null;
  const accItem = equippedItems['소품'] ? getItemById(equippedItems['소품']!) : null;
  const bgItem = equippedItems['배경'] ? getItemById(equippedItems['배경']!) : null;

  return (
    <View style={styles.container}>
      {/* Background Decor */}
      {bgItem && (
        <View style={styles.backgroundDecor}>
          <Text style={{ fontSize: cfg.size * 1.2 }}>{bgItem.emoji}</Text>
        </View>
      )}

      <Animated.View style={[styles.characterWrap, { width: cfg.container, height: cfg.container }, containerStyle]}>
        {/* Wings Decor (Behind character) */}
        {wingItem && (
          <View style={[styles.wingDecor, { top: cfg.size * 0.2 }]}>
            <Text style={{ fontSize: cfg.size * 0.8 }}>{wingItem.emoji}</Text>
          </View>
        )}

        {/* 
          Using the high-quality PNG generated by the AI Designer 
          to ensure 100% parity with the improvement plan.
        */}
        <Image 
          source={require('@/assets/fairy_v2.png')} 
          style={{ 
            width: cfg.size, 
            height: cfg.size,
            borderRadius: cfg.size / 2, // Ensure it looks good if there's a slight edge
          }}
          resizeMode="contain"
        />

        {/* Hat Decor (On top) */}
        {hatItem && (
          <View style={[styles.hatDecor, { top: -cfg.size * 0.15 }]}>
            <Text style={{ fontSize: cfg.size * 0.4 }}>{hatItem.emoji}</Text>
          </View>
        )}

        {/* Accessory Decor (Side) */}
        {accItem && (
          <View style={[styles.accDecor, { right: -cfg.size * 0.1, bottom: cfg.size * 0.1 }]}>
            <Text style={{ fontSize: cfg.size * 0.4 }}>{accItem.emoji}</Text>
          </View>
        )}
      </Animated.View>

      {/* Message Bubble */}
      {showMessage && message && (
        <Animated.View 
          entering={ZoomIn.duration(400).springify()}
          style={styles.bubble}
        >
          <View style={styles.bubbleTail} />
          <Text style={styles.bubbleText}>{message}</Text>
        </Animated.View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  characterWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  hatDecor: {
    position: 'absolute',
    zIndex: 20,
  },
  wingDecor: {
    position: 'absolute',
    zIndex: 5,
    opacity: 0.8,
  },
  accDecor: {
    position: 'absolute',
    zIndex: 20,
  },
  backgroundDecor: {
    position: 'absolute',
    zIndex: 1,
    opacity: 0.3,
  },
  bubble: {
    marginTop: 8,
    backgroundColor: 'white',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    maxWidth: 280,
  },
  bubbleTail: {
    position: 'absolute',
    top: -6,
    left: '50%',
    marginLeft: -6,
    width: 12,
    height: 12,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#E5E7EB',
    transform: [{ rotate: '45deg' }],
  },
  bubbleText: {
    fontSize: 15,
    color: '#374151',
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: 'Jua',
  },
});
